name: 'Docker build'
description: 'Build and Push the image'
inputs:
  repository:
    required: false
    default: 'ghcr.io'
    description: 'Repository URL'
  username:
    required: false
    description: 'Repository Username'
  password:
    required: false
    description: 'Repository Password'
  image-name:
    required: true
    description: 'Image name'
  image-version:
    default: ${{ github.ref_name }}
    description: 'Image Version'
  push:
    default: 'false'
    description: 'Should the image be pushed to the repo'
  srtla-branch:
    default: 'main'
    description: 'SRTla branch to build from (main/next)'
  sls-tag:
    default: 'latest'
    description: 'SRT-Live-Server tag to use (latest/next)'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      if: ${{ inputs.username && inputs.password }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.repository }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    
    # Determine additional tag based on release type
    - name: Set additional tag
      id: set-tag
      shell: bash
      run: |
        # Check if this is a pre-release
        if [[ "${{ github.event_name }}" == "release" && "${{ github.event.release.prerelease }}" == "true" ]]; then
          echo "TAG=next" >> $GITHUB_OUTPUT
          echo "Pre-release detected: using next tag"
        else
          echo "TAG=latest" >> $GITHUB_OUTPUT
          echo "Stable release detected: using latest tag"
        fi

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        build-args: |
          SRTLA_BRANCH=${{ inputs.srtla-branch }}
          SLS_TAG=${{ inputs.sls-tag }}
        tags: |
          ${{ inputs.repository }}/${{ inputs.image-name }}:${{ inputs.image-version }}
          ${{ inputs.repository }}/${{ inputs.image-name }}:${{ steps.set-tag.outputs.TAG }}
        push: ${{ inputs.push == 'true' }}
        cache-from: type=gha,scope=${{ inputs.image-name }}-${{ inputs.image-version }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}-${{ inputs.image-version }}